baseURL = 'https://daniellerche.dk/'
languageCode = 'en-us'
title = 'A personal blog'
theme = 'paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'MiniBossDK'                     # github.com/YOUR_GITHUB_ID
  linkedin = 'daniel-lerche-2834601b2'      # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwallpaperaccess.com%2Ffull%2F2565248.jpg&f=1&nofb=1&ipt=cd91ec2a98823403c33e001cef59229899e1265b6719cac76a464d8a39f54ec1&ipo=images'                 # gravatar email or image url
  name = 'Daniel Lerche'
  bio = 'Doogo'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon